{% set name = "neptune-prophet" %}
{% set package_name = "neptune_prophet" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: 5d022c747ac81ea1aa2230ded5f5d7add2454aff12f9a1d0eb4a17d4859ff30f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.7
    - matplotlib-base <=3.4.3
    - neptune-client >=0.15.0
    - numpy
    - pandas
    - prophet >=1.0
    - scipy
    - statsmodels

test:
  imports:
    - neptune_prophet
    - neptune_prophet.impl
  requires:
    - pip
    - pytest
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Prophet
  doc_url: https://docs.neptune.ai/integrations-and-supported-tools/
  dev_url: https://github.com/neptune-ai/neptune-prophet

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - shnela
    - Raalsky
    - twolodzko
    - AleksanderWWW
    - PatrykGala
